In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import cv2
import sys
sys.path.append(".")
sys.path.append("..")
from datasetloader.data_loader_MSRAHT import MSRA_HT
from utils.hand_detector import HandDetector

In [93]:
rot = torch.randn(778,3).unsqueeze(0)
scale = torch.randn(1)
trans = torch.randn(2).unsqueeze(0)

In [95]:
print(rot.shape)
print(scale.shape)
print(trans.shape)

torch.Size([1, 778, 3])
torch.Size([1])
torch.Size([1, 2])


In [92]:
scale.unsqueeze(0).unsqueeze(1)

tensor([[[1.4301]]])

In [103]:
trans.unsqueeze(0)

tensor([[[0.2715, 0.5635]]])

In [101]:
rot[:,:,:2]*scale.unsqueeze(0).unsqueeze(1)

tensor([[[-5.3810, -1.2348],
         [ 2.4118,  3.1869],
         [ 1.4056,  4.6517],
         ...,
         [-4.0475,  0.3826],
         [-1.7148,  5.4869],
         [-5.7752,  2.3516]]])